---
root: true
parser: '@typescript-eslint/parser'
env:
  es6: true
  node: true
  jest: true
extends:
  - eslint-config-airbnb-base
  - eslint-config-airbnb-base/rules/strict
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-function-return-type':
    ['error', { allowTypedFunctionExpressions: true, allowExpressions: true }]
  '@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }]
  '@typescript-eslint/explicit-member-accessibility': 'off'
  default-case: 'off'
  consistent-return: 'off'
  import/export: 'off'
  import/order: ['error', { newlines-between: 'always' }]
  import/prefer-default-export: 'off'
